# Jekyll Configuration

title: JGS Boilerplate
email: adejair.junioroulook@gmail.com
description: > 
  JGS is a simple boilerplate that englobes Jekyll, Gulp and Stylus, Thank's for use !!
baseurl: "" 
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: adejairjunior1
github_username:  Adejair

# Processor markdown
markdown: kramdown
# Set sub url with title of article markdown.
permalink: /:title